# Generated by Django 4.2 on 2024-03-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='days',
            options={'verbose_name': 'День', 'verbose_name_plural': 'Дни'},
        ),
        migrations.AlterModelOptions(
            name='workdaysschedule',
            options={'verbose_name': 'Расписание рабочих дней', 'verbose_name_plural': 'Расписание рабочих дней'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'Рабочий график', 'verbose_name_plural': 'Рабочие графики'},
        ),
    ]
