# Generated by Django 4.2 on 2024-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_alter_days_options_alter_workdaysschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='date',
            field=models.CharField(max_length=150, verbose_name='Дата'),
        ),
    ]
