# Generated by Django 4.2.5 on 2024-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_alter_days_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='datetime_end',
            field=models.TimeField(verbose_name='Конец времени'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='datetime_start',
            field=models.TimeField(verbose_name='Начало времени'),
        ),
    ]
